# Generated by Django 6.0.3 on 2026-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.AddField(
            model_name='donor',
            name='area',
            field=models.CharField(choices=[('Tirupati', 'Tirupati'), ('Renigunta', 'Renigunta'), ('Chandragiri', 'Chandragiri'), ('Tiruchanoor', 'Tiruchanoor'), ('Alipiri', 'Alipiri'), ('Mangalam', 'Mangalam')], default='tirupati', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
