# Generated by Django 6.0.3 on 2026-03-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_created_at_donor_last_donation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('area', models.CharField(choices=[('Tirupati', 'Tirupati'), ('Renigunta', 'Renigunta'), ('Chandragiri', 'Chandragiri'), ('Tiruchanoor', 'Tiruchanoor'), ('Alipiri', 'Alipiri'), ('Mangalam', 'Mangalam')], max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
